name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    name: Build Checks
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Build, Test, and Lint
        uses: remedyred/check-action@v1.1.14
        with:
          SCRIPTS: build,lint,test,docs,schema
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}